// GENERATED by scripts/generate-agent-catalog.mjs — do not edit.
// Source: public/shared/provider-catalog/catalog/current.yaml, the repo's single pricing source of truth.
// CATALOG_SHA256 is the sha256 of those exact catalog bytes; the drift test in
// tests/catalog.drift.runtime.mjs fails until the generator is re-run.
//
// Included: every USD row the catalog prices region-agnostically (region:
// global). Field mapping, catalog key -> TypeScript field:
//   input_per_million             -> inputPerMillion
//   output_per_million            -> outputPerMillion
//   cache_read_input_per_million  -> cacheReadPerMillion (null -> 0; the row
//                                   states no separate rate for that class)
//   cache_write_input_per_million -> cacheWritePerMillion (null -> 0; same)
//   reasoning_output_per_million  -> reasoningPerMillion (null -> the output
//                                   rate, because catalogCost subtracts
//                                   reasoning tokens out of output and a 0
//                                   would price thinking tokens as free)
// Not modeled: 1h cache-write rates, batch discounts, cache storage, and
// long-context multipliers. These numbers are standard-tier public list-price
// subtotals, never an invoice.
export const CATALOG_SHA256 = "2f7be1807bdffc39acb9bda0b6e601863b1826f43b4e8d4d75d7bc687da8b44d";

export interface CatalogPrice {
  inputPerMillion: number;
  outputPerMillion: number;
  cacheReadPerMillion: number;
  cacheWritePerMillion: number;
  reasoningPerMillion: number;
}

const PRICES: Readonly<Record<string, CatalogPrice>> = Object.freeze({
  "anthropic/claude-haiku-4-5": Object.freeze({
    inputPerMillion: 1,
    outputPerMillion: 5,
    cacheReadPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
    reasoningPerMillion: 5,
  }),
  "anthropic/claude-haiku-4-5-20251001": Object.freeze({
    inputPerMillion: 1,
    outputPerMillion: 5,
    cacheReadPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
    reasoningPerMillion: 5,
  }),
  "anthropic/claude-opus-4-1": Object.freeze({
    inputPerMillion: 15,
    outputPerMillion: 75,
    cacheReadPerMillion: 1.5,
    cacheWritePerMillion: 18.75,
    reasoningPerMillion: 75,
  }),
  "anthropic/claude-opus-4-8": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 25,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    reasoningPerMillion: 25,
  }),
  "anthropic/claude-opus-5": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 25,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    reasoningPerMillion: 25,
  }),
  "anthropic/claude-sonnet-4-5": Object.freeze({
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    reasoningPerMillion: 15,
  }),
  "anthropic/claude-sonnet-4-5-20250929": Object.freeze({
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    reasoningPerMillion: 15,
  }),
  "anthropic/claude-sonnet-4-6": Object.freeze({
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    reasoningPerMillion: 15,
  }),
  "anthropic/claude-sonnet-5": Object.freeze({
    inputPerMillion: 2,
    outputPerMillion: 10,
    cacheReadPerMillion: 0.2,
    cacheWritePerMillion: 2.5,
    reasoningPerMillion: 10,
  }),
  "gemini/gemini-2.5-flash": Object.freeze({
    inputPerMillion: 0.3,
    outputPerMillion: 2.5,
    cacheReadPerMillion: 0.03,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 2.5,
  }),
  "gemini/gemini-2.5-pro": Object.freeze({
    inputPerMillion: 1.25,
    outputPerMillion: 10,
    cacheReadPerMillion: 0.125,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 10,
  }),
  "openai/gpt-5.4-mini": Object.freeze({
    inputPerMillion: 0.75,
    outputPerMillion: 4.5,
    cacheReadPerMillion: 0.075,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 4.5,
  }),
  "openai/gpt-5.4-mini-2026-03-17": Object.freeze({
    inputPerMillion: 0.75,
    outputPerMillion: 4.5,
    cacheReadPerMillion: 0.075,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 4.5,
  }),
  "openai/gpt-5.4-nano": Object.freeze({
    inputPerMillion: 0.2,
    outputPerMillion: 1.25,
    cacheReadPerMillion: 0.02,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 1.25,
  }),
  "openai/gpt-5.4-nano-2026-03-17": Object.freeze({
    inputPerMillion: 0.2,
    outputPerMillion: 1.25,
    cacheReadPerMillion: 0.02,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 1.25,
  }),
  "openai/gpt-5.5": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 30,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 30,
  }),
  "openai/gpt-5.5-2026-04-23": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 30,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 30,
  }),
  "openai/gpt-5.6": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 30,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    reasoningPerMillion: 30,
  }),
  "openai/gpt-5.6-sol": Object.freeze({
    inputPerMillion: 5,
    outputPerMillion: 30,
    cacheReadPerMillion: 0.5,
    cacheWritePerMillion: 6.25,
    reasoningPerMillion: 30,
  }),
  "openai/text-embedding-3-large": Object.freeze({
    inputPerMillion: 0.13,
    outputPerMillion: 0,
    cacheReadPerMillion: 0,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 0,
  }),
  "openai/text-embedding-3-small": Object.freeze({
    inputPerMillion: 0.02,
    outputPerMillion: 0,
    cacheReadPerMillion: 0,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 0,
  }),
  "vertex/claude-haiku-4-5@20251001": Object.freeze({
    inputPerMillion: 1,
    outputPerMillion: 5,
    cacheReadPerMillion: 0.1,
    cacheWritePerMillion: 1.25,
    reasoningPerMillion: 5,
  }),
  "vertex/claude-sonnet-4-6": Object.freeze({
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheReadPerMillion: 0.3,
    cacheWritePerMillion: 3.75,
    reasoningPerMillion: 15,
  }),
  "vertex/gemini-2.5-flash": Object.freeze({
    inputPerMillion: 0.3,
    outputPerMillion: 2.5,
    cacheReadPerMillion: 0.03,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 2.5,
  }),
  "vertex/gemini-2.5-pro": Object.freeze({
    inputPerMillion: 1.25,
    outputPerMillion: 10,
    cacheReadPerMillion: 0.125,
    cacheWritePerMillion: 0,
    reasoningPerMillion: 10,
  }),
});

// Rows deliberately absent above. A regional rate is not a region-free
// rate, so these are omitted rather than borrowed; a run on one of these
// models prices as unpriced (honest zero) instead of plausibly wrong.
//   bedrock/anthropic.claude-3-5-haiku-20241022-v1:0 — priced per region only (us-east-1)
//   bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0 — priced per region only (us-east-1)
//   bedrock/global.amazon.nova-2-lite-v1:0 — priced per region only (us-east-1)
//   bedrock/global.anthropic.claude-haiku-4-5-20251001-v1:0 — priced per region only (us-east-1)
//   bedrock/global.anthropic.claude-opus-4-8 — priced per region only (us-east-1)
//   bedrock/global.anthropic.claude-sonnet-4-6 — priced per region only (us-east-1)
//   bedrock/mistral.ministral-3-8b-instruct — priced per region only (ap-northeast-1, ap-south-1, ap-southeast-2, eu-south-1, eu-west-1, eu-west-2, sa-east-1, us-east-1, us-east-2, us-west-2)
//   bedrock/mistral.mistral-large-3-675b-instruct — priced per region only (ap-northeast-1, ap-south-1, ap-southeast-2, sa-east-1, us-east-1, us-east-2, us-west-2)
//   bedrock/us.meta.llama4-maverick-17b-instruct-v1:0 — priced per region only (us-east-1)
//   bedrock/us.meta.llama4-scout-17b-instruct-v1:0 — priced per region only (us-east-1)

function catalogProvider(provider: string): string {
  // Runtime provider IDs come from Pi; catalog IDs name billing surfaces.
  if (provider === "google") return "gemini";
  if (provider === "google-vertex") return "vertex";
  return provider;
}

export function catalogSearchCeiling(
  model: string,
  inputTokens: number,
  outputTokens: number,
): number | undefined {
  const slash = model.indexOf("/");
  const normalized = slash < 0
    ? model
    : `${catalogProvider(model.slice(0, slash))}/${model.slice(slash + 1)}`;
  const price = PRICES[normalized];
  if (!price || !Number.isSafeInteger(inputTokens) || inputTokens < 0 ||
      !Number.isSafeInteger(outputTokens) || outputTokens < 0) {
    return undefined;
  }
  const worstInputRate = Math.max(price.inputPerMillion, price.cacheWritePerMillion);
  const worstOutputRate = Math.max(price.outputPerMillion, price.reasoningPerMillion);
  const usd = (inputTokens * worstInputRate + outputTokens * worstOutputRate) / 1_000_000;
  return Math.ceil(usd * 1e10) / 1e10;
}

export function catalogCost(usage: {
  provider: string;
  model: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  reasoningTokens: number;
}): { priced: boolean; usd: number } {
  const provider = catalogProvider(usage.provider);
  const price = PRICES[`${provider}/${usage.model}`];
  if (!price) return { priced: false, usd: 0 };
  // Pi normalizes input as uncached input. cacheRead/cacheWrite are disjoint
  // classes, while reasoning remains a subset of output.
  const billableInput = usage.inputTokens;
  const visibleOutput = usage.outputTokens - usage.reasoningTokens;
  if (
    billableInput < 0 ||
    visibleOutput < 0 ||
    Object.values(usage).some((value) => typeof value === "number" && (!Number.isSafeInteger(value) || value < 0))
  ) {
    return { priced: false, usd: 0 };
  }
  const usd = (
    billableInput * price.inputPerMillion +
    usage.cacheReadTokens * price.cacheReadPerMillion +
    usage.cacheWriteTokens * price.cacheWritePerMillion +
    visibleOutput * price.outputPerMillion +
    usage.reasoningTokens * price.reasoningPerMillion
  ) / 1_000_000;
  return { priced: true, usd: Math.round((usd + Number.EPSILON) * 1e10) / 1e10 };
}
