export const FRAMEWORK_VERSION = "0.1.0";
export const PI_ADAPTER_VERSION = FRAMEWORK_VERSION;
export const PI_UPSTREAM_VERSION = "0.83.0";
export const CLAUDE_ADAPTER_VERSION = FRAMEWORK_VERSION;
export const CLAUDE_AGENT_SDK_VERSION = "0.3.220";
export const CLAUDE_CODE_VERSION = "2.1.220";
export const CLAUDE_UPSTREAM_VERSION =
  `agent-sdk-${CLAUDE_AGENT_SDK_VERSION}+claude-code-${CLAUDE_CODE_VERSION}`;
